### ISSUE TITLE
Get working on Windows

### ISSUE THREAD

**Issue by bradrn** [Lemmih/reanimate#1]
Is there any way to get this working on Windows? Here's what I've tried so far:

1. The first problem is the `unix` dependency, which oddly enough doesn't actually seem to be used anywhere. After removing it I was able to build `reanimate` fine.
2. After building I tried to run the provided `latex_color.hs` example, but got the following output (with other actions I did in `  [indented square brackets]`):
```
> stack .\latex_color.hs
Failed to open browser. Manually visit: C:\Users\bradn\Documents\Haskell\reanimate\.stack-work\install\b7328101\share\x86_64-windows-ghc-8.2.2\reanimate-0.1.4.1\viewer/build/index.html
  [Here I manually visited the given location]
Server pending.
Found self. Listening.
Kill and respawn.
  [Here I refreshed the page on my web browser]
Server pending.
latex_color.hs: CloseRequest 1001 ""
Found self. Listening.
Kill and respawn.
latex_color.hs: DeleteFile "C:\\Users\\bradn\\AppData\\Local\\Temp\\reanimate-XXXXXX35312-1.exe": permission denied (Access is denied.)
latex_color.hs: C:\Users\bradn\AppData\Local\Temp\reanimate-XXXXXX35312-2.exe: runInteractiveProcess: invalid argument (Exec format error)
```
3. After the `permission denied` error above, I tried running as an administator, and got the following output instead:
```
> stack .\latex_color.hs
Failed to open browser. Manually visit: C:\Users\bradn\Documents\Haskell\reanimate\.stack-work\install\b7328101\share\x86_64-windows-ghc-8.2.2\reanimate-0.1.4.1\viewer/build/index.html
Server pending.
Found self. Listening.
Kill and respawn.
  [Here I manually visited the given location]
Server pending.
Found self. Listening.
Kill and respawn.
latex_color.hs: C:\Users\bradn\AppData\Local\Temp\reanimate-XXXXXX30972-2.exe: runInteractiveProcess: invalid argument (Exec format error)
```

**Comment by bradrn** [comment]
Actually, it seems that I was a bit hasty in my last try. It turns out that if you wait a bit longer and ignore the errors, the Playground works just fine, including the live code update. There's still lots of errors though; it would be nice to get rid of them. There's also still the problem of the `unix` dependency which prevents Windows compilation; is there any reason why that cannot be removed?

**Comment by bradrn** [comment]
Well, I've done a bit of digging, and it looks like most of the 'errors' above were just normal messages which I misinterpreted as errors. (Suggestion: rephrase these messages to make this more obvious so other people don't make that same mistake.) However, there are some genuine problems on Windows:

- [ ] Unused `unix` dependency prevents Windows compilation. Fix: remove dependency, since it doesn't appear to be doing anything.
- [ ] Browser isn't opening on Windows. Fix: use the [`open-browser`](http://hackage.haskell.org/package/open-browser) package, or add `"start"` (the Windows command) to [`Reanimate.Driver.openBrowser`](https://github.com/Lemmih/reanimate/blob/master/src/Reanimate/Driver.hs#L90-L98).
- [ ] Weird errors with `DeleteFile` and `runInteractiveProcess` (see above for exact error messages). Fix: I'm really not sure, actually. I think it's a problem with a dependency (possibly `fsnotify`), not with `reanimate` itself.

**Comment by bradrn** [comment]
Since #2 has been merged the HEAD of reanimate now compiles and works on Windows. However, the weird file errors are still there, so I won't close this issue just yet.

**Comment by Lemmih** [comment]
Do you know why the errors happen? Is it something we can test for?

**Comment by Lemmih** [comment]
For me, it happens when I reload the browser window but not when changes are detected via fsnotify. No idea why this is so, though.

**Comment by Lemmih** [comment]
Hi @bradrn. I've fixed a few race conditions in the driver and now everything works smoothly for me on Windows. If it also works for you then I'd like to close this issue.

**Comment by bradrn** [comment]
Hi @Lemmih, thanks so much for fixing this! Unfortunately I don’t have enough time just right now to test it, but in a few hours when I get home I will definitely try it out.

**Comment by Lemmih** [comment]
Sigh, I spoke too early. I still see the same errors.

**Comment by Lemmih** [comment]
Ok, now I've fixed the last issues (I think). Everything works as well on Windows as it does on Linux for me. Code reloads, refreshing the browser, latex output, etc.

**Comment by Lemmih** [comment]
Everything looks to be solved. Closing issue.

**Comment by bradrn** [comment]
That’s fine @Lemmih.
