### ISSUE TITLE
Couldn't cabal-install Reanimate library (2 errors when compiling Reanimate.Svg.Unuse)

### ISSUE THREAD

**Issue by LessnessRandomness** [Lemmih/reanimate#28]
Hello, I'm newbie. I couldn't cabal-install Reanimate library: https://prnt.sc/pxyqrs - got two errors when compiling Reanimate.Svg.Unuse.
 
Is it fixable? If yes, how and what did I do wrong?
Thanks in advance.

**Comment by Lemmih** [comment]
Oops, my bad. It should be fixed now. It shouldn't happen again but if it does, you can use 'stack' to make everything magically work.

**Comment by LessnessRandomness** [comment]
Thank you!
