### ISSUE TITLE
Document key commands of the web viewer

### ISSUE THREAD

**Issue by jhrcek** [Lemmih/reanimate#34]
The [Driver haddocks](http://hackage.haskell.org/package/reanimate-0.1.9.0/docs/Reanimate.html#g:1) mention some key commands

> Key commands for pausing, frame stepping, forward/rewind.

Could you please recommend the available key commands in the haddocks? 
Maybe it would be even better if those commands were discoverable in the web ui itself (via help link? As buttons?)

**Comment by Lemmih** [comment]
Right now the hotkeys are:

[space]: pause/unpause
[left]: move one frame backward
[right]: move one frame forward.
[down]: move 10 frames backward.
[up]: move 10 frames forward.

The web ui is quite janky right now. PRs for both documentation and the web ui itself are most welcome. :)

**Comment by jhrcek** [comment]
I'll add mention of those (an also space) in the haddocks. But I'm not really friends with JS. Would you be open to me rewriting the UI in something like elm / purescript?

**Comment by Lemmih** [comment]
Rewriting the UI in something more maintainable would be great. Elm looks like a perfect fit for this.

**Comment by jhrcek** [comment]
Alright, I'll try to reverse engineer the current viewer and attempt to rewrite it in elm

**Comment by Lemmih** [comment]
I'd love to help and learn elm. I've created a new branch for this development: feature-elm-ui. Apparently https://github.com/billstclair/elm-websocket-client is the best (only?) websocket package for elm-0.19 and it looks quite complicated to me. Think you could create an elm app that connects to 'ws://localhost:9161' and just logs the incoming messages?

Right now, the haskell websocket server send each frame in a separate message, with the format '[frame number][svg data]'. We should probably use a more principled format.

**Comment by jhrcek** [comment]
Yes, that's currently the "best" WS package I'm aware of. Unfortunately there is currently no "blessed" websocket package for 0.19. Since 0.19, elm only allows native JS  code in kernel packages (= those in [elm](https://github.com/elm) and [elm-explorations](https://github.com/elm-explorations), maintained by the core elm people) , which leaves the [ports](https://guide.elm-lang.org/interop/ports.html) as the only supported way to interact with JS. This means that we'll have to work with mix of elm + small amount of JS as mentioned in the package you linked.

> Think you could create an elm app that connects to 'ws://localhost:9161' and just logs the incoming messages?

Sure, I'll give it a go and create a PR within a day or two.

**Comment by Lemmih** [comment]
I adapted the example from the elm websocket package. It's not much but it can show the svgs so that's a start.

**Comment by jhrcek** [comment]
Wow, really nice work :+1: Especially since you had to deal with that elm-websocket-client, which - now that I'm looking at it more closely -  really doesn't have well designed API and has some weird portfunnel machinery, which seems to be overkill for this simple use case (compare to the official [websockets](https://old.elm.dmy.fr/packages/elm-lang/websocket/1.0.2/WebSocket) that was available for elm 0.18). Should I pick this up and look for ways to improve it? At the minimum I could reduce a lot of unnecessary fluff around the ports logic, some unused code and dependencies etc.

Also I'm sorry that your first experience with elm was this (speaking from the position of fulltime elm frontend dev). Most of the elm packages are rather nice and well designed and elm, in general is joy to work with. But the JS interop is not as good as in e.g. purescript and the support for often used web APIs is still kindof lacking.

**Comment by jhrcek** [comment]
I couldn't stand the port funnel thing so I started where you left off, rewriting to use simpler [websockets](https://package.elm-lang.org/packages/bburdette/websocket/) package which should suffice for this use case. It will need ton more work, but in the end it's gonna be shorter, more lightweight and more typesafe than the current react solution. So fart no PR open, I'll continue working on it on my private fork https://github.com/jhrcek/reanimate/commits/feature-elm-ui

**Comment by Lemmih** [comment]
Please feel free to push to the branch in the main repo.

**Comment by jhrcek** [comment]
Thanks for the access. I'll work on it over the weekend. In the meantime can you share your idea about what the viewer should eventually be able to do? Should I try to emulate the behavior of the current react viewer?

**Comment by Lemmih** [comment]
Here's how I imagine it:

 * Frames should take up the entire viewport (or as much as their aspect ratio allows).
 * Frames should be prefetched. It looks like elm doesn't support the 'link' html element. Can we use something else here?
 * HUD / status line should contain information such as frame count, current frame, rendered frames, actual fps (some svg images are too complex to be displayed at 60 fps).
 * A pop-up help screen that lists key bindings.

**Comment by jhrcek** [comment]
I've made reasonable progress today and pushed my work on [feature-elm-ui-2](https://github.com/Lemmih/reanimate/commit/9a5a71bb0a3e447ffd8b392825df9f0b575e311f)

The viewer should look similar to the current react viewer, with some exceptions:
- fps meter not implemented yet
- keyboard shortcuts not implemented yet (instead I placed explicit buttons for pausing / rewinding etc.).

> Frames should be prefetched. It looks like elm doesn't support the 'link' html element. Can we use something else here?

You can do link in elm too. There's no explicit function for Html module, but you can define it yourself using [Html.node](https://package.elm-lang.org/packages/elm/html/latest/Html#node). I'm not that familiar with prefetching, so I'm not sure how including links could help. Could you clarify please?

If you want to play with my version of viewer, you can use steps like these with my branch:
```bash
stack build
./example/boundingbox.hs
```
Tomorrow I'll add the missing features.

**Comment by Lemmih** [comment]
> I added one difference in behavior:
> 
> * when all the frames are not loaded, progress bar is shown and the pausing/seeking controls are disabled. I only enable them after all the frames are loaded.

I think it would make sense if the controls were available before all frames are loaded. Some animations can take a long time to render and the controls are useful even the frame rate is less than 60fps.

**Comment by jhrcek** [comment]
You're right :+1:  I removed the intermediate `ReceivingFrames` state and enabled the player controls always and it works quite nicely.

I originally added that intermediate state to
- distinguish between "we have all frames" and "some frames are still missing" and I disabled player controls because stepping by 1 / 10 frames can lead to nothing happening. But I guess this way it's better and much simpler.

I pushed it with some further simplifications to your PR branch. I like how it's shaping up so far! I'm still gonna add FPS meter, help button and keyboard shortcuts..

**Comment by jhrcek** [comment]
Keyboard navigation added.

One thing I remembered: when building the elm app for inclusion to cabal package, you might want to minify the javascript output. See instructions in `viewer-elm/README.md`. This reduces the JS size from ~ 140KB to ~ 40KB

**Comment by Lemmih** [comment]
Looking good. Way more readable and extendable than the reactjs implementation.

**Comment by jhrcek** [comment]
Thanks :) Help dialog added. Please note that I suck at UI design, so it looks kind of primitive, but I guess it aligns well with the rest of th
is simplistic viewer.

![help](https://user-images.githubusercontent.com/2716069/70862815-8866df80-1f41-11ea-8edc-fbb1b7ef1a0e.gif)

**Comment by jhrcek** [comment]
I added FPS view and I'm done for today. The UI feels quite solid to me for a first draft :-) Let me know what you think and if there's something more you'd like to add.

**Comment by Lemmih** [comment]
Looks great. The white text becomes invisible if the animation uses a white background, though. See doc_drawBox.hs for an example of this. And I'd like the FPS counter to ignore missing frames and gradually increase as more frames are loaded. In the previous viewer, I used the FPS counter as a guide to how smooth I should expect the animation to be before it loaded completely. The progress bar does a very similar job but it is nice to have an accurate number.

The FPS counter is not too important, though, so I'll give the text a semi-transparent background and merge the PR tomorrow. Thanks for all the good work. It's been interesting seeing how elm works and I hope you'll send me more PRs in the future. :)

**Comment by jhrcek** [comment]
>The white text becomes invisible if the animation uses a white background

I must have forgotten to add background color when moving the styles to separate css file. So yes, please, add the semi-transparent background.

> I'd like the FPS counter to ignore missing frames and gradually increase as more frames are loaded

I'll look into that in followup PRs. Now I'd like to spend some time playing with the library itself :smile: 

Elm is great. Although it's lack of type-classes and higher-kinded polymorphism sometimes lead to 
quite some boilerplate (i often wish I had functor, traversable and lenses), it naturally leads you to simple and easy to maintain programs. Also the tooling - elm compiler itself with lightning compilation speed, elm-format and elm-live make for fast and pleasant development experience for simple stuff.

P.S.: In your haskellers.com profile I read: "My free time is spent unicycling, juggling, and, of course, writing Haskell code." - I did all of those things too for quite some time :laughing: But about 8 years ago I switched from unicycling to parkour and I haven't switched ever since.

**Comment by Lemmih** [comment]
> P.S.: In your haskellers.com profile I read: "My free time is spent unicycling, juggling, and, of course, writing Haskell code." - I did all of those things too for quite some time laughing But about 8 years ago I switched from unicycling to parkour and I haven't switched ever since.

Great minds think alike. :)
