### ISSUE TITLE
cabal exec -- ghc *\fourier.hs 

### ISSUE THREAD

**Issue by Tridu33** [Lemmih/reanimate#4]
reanimate-master\examples\fourier.hs:36:12: error:
? Variable not in scope:
signal :: Integer -> Double -> Frame Double
? Perhaps you meant ‘signum’ (imported from Prelude)
|
36 | phi <- signal 0 (2*pi)
| ^^^^^^

**Comment by Lemmih** [comment]
Hi Tridu33,

The example has been updated to reflect the API changes.
