### ISSUE TITLE
Document limitation or expand implementation of pathify

### ISSUE THREAD

**Issue by jhrcek** [Lemmih/reanimate#46]
It's not clear that pathify only works on circles/rectangles/lines. Is there a technical reason why it doesn't work e.g. on polylines, polygons or ellipses? This limitation should be either documented or the missing functionality should be implemented. I can tackle these, but I need to know which is the case.

**Comment by Lemmih** [comment]
No technical reason. I just only bothered implementing it for the shapes I happened to be using.
