### ISSUE TITLE
Different animations: in browser vs rendered

### ISSUE THREAD

**Issue by irisyupingren** [Lemmih/reanimate#59]
Here are two clips I generated using your package (very nice piece of work!):
![rendered](https://user-images.githubusercontent.com/8770294/74979615-3fdf0d00-542f-11ea-8836-aa1e35152e3f.gif)
![browser](https://user-images.githubusercontent.com/8770294/74979618-41103a00-542f-11ea-852e-f06a98eeea0e.gif)

The problem is, they are generated using the same code with only one difference, the render flag.

My code is based on the tut_glue_animate example. 
https://gist.github.com/irisyupingren/aea8716904ea511dd1f66ffa6c382918

**Comment by Lemmih** [comment]
The background defaults to transparent but this doesn't work well in normal videos (it will work in gifs, though). When you render an mp4 with a transparent background, it'll default to black and you'll see ghosts of all the shapes you draw. The exact behaviour depends on the versions of ffmpeg and rsvg.

Try adding 'mkBackground "black"' to your 'env'.

**Comment by irisyupingren** [comment]
Yes, adding the background colour fixed it. Thank you!
