### ISSUE TITLE
Create organization.

### ISSUE THREAD

**Issue by Lemmih** [Lemmih/reanimate#65]
It seems the name 'reanimate' is already taken but that user-account looks inactive. Hi @reanimate, if you don't use your account, may I have it?

**Comment by reanimate** [comment]
*yawn, huh, who dares wake me from the dead!

**Comment by Lemmih** [comment]
Welcome back to the land of the living. :)

I'm thinking I'll name the organization 'reanimate-svg' since your account isn't inactive.

**Comment by reanimate** [comment]
It's most certainly inactive, I didn't even remember it existed until I got your email :man_shrugging:

**Comment by Lemmih** [comment]
In that case, I would be eternally grateful if you could find it in your heart to donate your account to be an umbrella organization for my favorite hobby project. I started this project because I enjoy science videos and want to animate a bunch of them myself. Here's [an example of the videos I make.](https://www.reddit.com/r/MapPorn/comments/f2ospv/oc_10_map_projections_and_how_they_distort_the/)

If you gave me your account, I could gather the various repositories I use under a single namespace. If you would rather not then I totally understand. It _is_ a wonderful user name. :)

**Comment by reanimate** [comment]
Sure email peter@geocode.earth
