### ISSUE TITLE
Rename Reanimate.Signals

### ISSUE THREAD

**Issue by Lemmih** [Lemmih/reanimate#74]
Pretty much all other animation libraries and frameworks call them easing functions. So rename Reanimate.Signals to Reanimate.Ease and also add more predefined easing functions from: https://easings.net/

**Comment by TristanCacqueray** [comment]
Should the `Signal = Double -> Double` be also renamed?

**Comment by Lemmih** [comment]
> Should the `Signal = Double -> Double` be also renamed?

Nah, let's leave the type as 'Signal' for now.
