### ISSUE TITLE
Add a verbose option for `reanimate`

### ISSUE THREAD

**Issue by expipiplus1** [Lemmih/reanimate#90]
It might be useful to see what's going on when code is reloaded.

**Comment by Lemmih** [comment]
Do you mean in the browser or as console output?

**Comment by Lemmih** [comment]
I've added a verbose option that prints out the location of the source code and prints commands before executing them.

**Comment by expipiplus1** [comment]
Ideally console I guess as then it doesn't depend on having a working
connection.

Will try it out, thanks!

**Comment by expipiplus1** [comment]
works for me
