### ISSUE TITLE
Can code reloading work without stack

### ISSUE THREAD

**Issue by expipiplus1** [Lemmih/reanimate#91]
It would be nice to be able to enjoy the code reloading without using stack. Perhaps just replacing "stack ghc ..." with "ghc ..." would work. An option for this would be super.

**Comment by Lemmih** [comment]
Hi Joe.
Added a flag for specifying the location of 'ghc'. When the flag is enabled, ghc will be used directly instead of going through stack. Let me know if it works for your setup.

**Comment by expipiplus1** [comment]
I'll give it a try. Thanks!

**Comment by expipiplus1** [comment]
Works very well!
