### ISSUE TITLE
Problem with Hmatrix installation: Blas and Lapack

### ISSUE THREAD

**Issue by Mathoholic** [Lemmih/reanimate#92]
While building reanimate in Windows 10, I am getting this error, though I searched on Stack Exchange and Google, it problem is due to improper installation of Scipy. But I checked that both Lapack and Blas are installed. I am using anaconda, so scipy gots installed automatically.

hmatrix          > configure
hmatrix          > Configuring hmatrix-0.20.0.0...
hmatrix          > Cabal-simple_Z6RU0evB_3.0.1.0_ghc-8.8.3.exe: Missing dependencies on foreign
hmatrix          > libraries:
hmatrix          > * Missing (or bad) C libraries: blas, lapack
hmatrix          > This problem can usually be solved by installing the system packages that
hmatrix          > provide these libraries (you may need the "-dev" versions). If the libraries
hmatrix          > are already installed but in a non-standard location then you can use the
hmatrix          > flags --extra-include-dirs= and --extra-lib-dirs= to specify where they are.If
hmatrix          > the library files do exist, it may contain errors that are caught by the C
hmatrix          > compiler at the preprocessing stage. In this case you can re-run configure
hmatrix          > with the verbosity flag -v3 to see the error messages.

`--  While building package hmatrix-0.20.0.0 using:
      C:\sr\setup-exe-cache\x86_64-windows\Cabal-simple_Z6RU0evB_3.0.1.0_ghc-8.8.3.exe --builddir=.stack-work\dist\29cc6475 configure --user --package-db=clear --package-db=global --package-db=C:\sr\snapshots\1758616a\pkgdb --libdir=C:\sr\snapshots\1758616a\lib --bindir=C:\sr\snapshots\1758616a\bin --datadir=C:\sr\snapshots\1758616a\share --libexecdir=C:\sr\snapshots\1758616a\libexec --sysconfdir=C:\sr\snapshots\1758616a\etc --docdir=C:\sr\snapshots\1758616a\doc\hmatrix-0.20.0.0 --htmldir=C:\sr\snapshots\1758616a\doc\hmatrix-0.20.0.0 --haddockdir=C:\sr\snapshots\1758616a\doc\hmatrix-0.20.0.0 --dependency=array=array-0.5.4.0 --dependency=base=base-4.13.0.0 --dependency=binary=binary-0.8.7.0 --dependency=bytestring=bytestring-0.10.10.0 --dependency=deepseq=deepseq-1.4.4.0 --dependency=random=random-1.1-CUqV1zxrwrE4K5XCdTZSYy --dependency=semigroups=semigroups-0.19.1-KswQSjRjA2JDrzoYmnhZUy --dependency=split=split-0.2.3.4-KyPtAwfJzED2zEIheQpqQL --dependency=storable-complex=storable-complex-0.2.3.0-Ar2v6n6lk14548CkBJ9DCu --dependency=vector=vector-0.12.1.2-AWRYcz9jfa25Avs2q9Jg9V -f-disable-default-paths -f-openblas --extra-include-dirs=C:\Users\kshan\AppData\Local\Programs\stack\x86_64-windows\msys2-20180531\mingw64\include --extra-lib-dirs=C:\Users\kshan\AppData\Local\Programs\stack\x86_64-windows\msys2-20180531\mingw64\lib --extra-lib-dirs=C:\Users\kshan\AppData\Local\Programs\stack\x86_64-windows\msys2-20180531\mingw64\bin --exact-configuration --ghc-option=-fhide-source-paths
    Process exited with code: ExitFailure 1`

Please help how I can workout this issue.

**Comment by Lemmih** [comment]
hmatrix is unfortunately incredibly difficult to install on Windows. For now, you can disable the hmatrix dependency like this: `stack build --flag reanimate:-hmatrix`
Without hmatrix, you won't have access to the more advanced morphing algorithms but that's not a huge loss.

I should probably disable hmatrix by default or disable it completely on windows.

**Comment by Mathoholic** [comment]
Thanks for reply @Lemmih , 
I checked the way reanimate can render animations, I would request you to please let me know the possible ways of installing it on Windows, this little loss will remain impression of loss to me. What possibly is going wrong with hmatrix in windows?

**Comment by Lemmih** [comment]
I don't do tech support for other people's software. Just install reanimate without hmatrix and I promise you won't know the difference.

**Comment by Mathoholic** [comment]
fine,  so the problem is with Windows, I thought It is something else.
Thanks.
